version: "3.8"
services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "3002:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - JWT_SECRET=secret
      - PORT=3001
      - DB_PORT=3002
      - DATABASE_URL=postgresql://root:root@localhost:3002/postgres
      # - DATABASE_URL=postgresql://postgres:postgres@localhost:3002/postgres?schema=public
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   container_name: app_frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   # depends_on:
  #     # - backend

volumes:
  db:
    driver: local